# Example Site settings

#google_analytics: UA-NNNNNNNN-N
title: Blog # site title
description: >- # site description
   Another worthless blog
# Profile settings
author:
  name: The world is always ending, relax. # author name
  bio: >- # tell to the world
   stop reading
  email: clearfoggy@pm.me # email adress
  avatar: https://oddfeed.github.io/blog/assets/img/avatar.jpg # change with your own avatar

# URL settings
url: "https://blog.alienate.earth" #
baseurl: 
permalink: /:title/
google_analytics: # leave it blank if not wish
fb_appid:

# THEME   
header_pages:
  - index.md
  - about.md
footer: '<a href="https://blog.alienate.earth/feed">RSS</a> // follow us on <a 
href="https://twitter.com/alienatefurther">twitter</a>'

style: light # dark (default) or light
# listen_for_clients_preferred_style: true # true or false (default)

plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-postfiles
